### PR TITLE
Fix bug with timestamp comparison.

### PR DESCRIPTION
**Pull request by jemiahlee**

### CODE REVIEW

**Comment by BuildNerd** [comment]
This pull request requires a code review.

One of the following reviewers must sign off: @chase-seibert

**Comment by jemiahlee** [comment]
Need to fix the failiure addressed by this PR before this will ever be a successful test run. :)

**Comment by jemiahlee** [comment]
GH is returning all of the datetimes in GMT, so I think it's ok to just chop it off rather than dealing with conversion.

**Comment by chase-seibert** [comment]
lgtm

**Pull request merged**
