### PR TITLE
Minor changes, plus fixing how the last commit timestamp is computed.

### PR DESCRIPTION
**Pull request by jemiahlee**

### CODE REVIEW

**Comment by jemiahlee** [comment]
The test hook still seems screwed up. For me it links to a /10 (pr number), and this isn't PR #10.

Anyway, here's the reasoning/proof that the old way of computing the commit date didn't work. If we look at a branch as reported by github, here are the dates:

screenshot 2016-08-15 15 33 30

But if we look at how to get this out of PyGithub, you can see that the way we were doing it (the first batch of dates in this next screenshot) doesn't work, but this code change does make it work:
screenshot 2016-08-15 15 20 14

**Comment by jemiahlee** [comment]
Turns out this isn't quite right either. This is better than the first, but it seems like it gives you the date/time of the commit, not when it was last updated (I removed a commit from this PR and the date/times haven't changed). Working on a different fix.

**Comment by jemiahlee** [comment]
Checking to see if another comment updates the `updated_at` field on the PR.

**Comment by jemiahlee** [comment]
Well it turns out it is a little worse than I thought. It seems to be doing some caching on these objects, and just assuming it has the correct `last_modified` value unless you basically force it to update its cache.

screenshot 2016-08-16 12 40 23

**Comment by jemiahlee** [comment]
Ok, I've updated the code to take advantage of the knowledge I gained above. After re-pushing the code, here's what it looks like when I run those snippets again:

screenshot 2016-08-16 13 18 48

**Comment by jemiahlee** [comment]
And after posting the comment, here's what it looks like:

screenshot 2016-08-16 13 20 12

**Comment by chase-seibert** [comment]
Actual lint error: `./lgtm/git.py:4:0:E101:dateutil_parser:dateutil_parser imported but unused`.

**Comment by BuildNerd** [comment]
This pull request requires a code review.

One of the following reviewers must sign off: @chase-seibert

**Comment by jemiahlee** [comment]
Well, this isn't quite right either. If you delay pushing your PR, the timestamp that this is reading is for the one when you last modified that commit.

**Comment by chase-seibert** [comment]
lgtm

**Pull request merged**
