### PR TITLE
Add support for +1

### PR DESCRIPTION
**Pull request by anamartinez**

### CODE REVIEW

**Comment by BuildNerd** [comment]
This pull request requires a code review.

One of the following reviewers must sign off: @chase-seibert @jemiahlee

**Comment by chase-seibert** [comment]
lgtm - FYI we also have to tweak the Jenkins jobs so that a +1 will actually fire the web hook.

**Comment by chase-seibert** [comment]
lgtm

**Comment by chase-seibert** [comment]
lgtm

**Pull request merged**
